### ISSUE TITLE
distributed GA

### ISSUE THREAD

**Issue by john-hu** [PyOCL/OpenCLGA#15]
As a user, I would like to connect all of my devices to run a single GA model.

**Comment by kilikkuo** [comment]
As now I could setup pyopencl env in my laptop & VM.
I'd like to design the framework.
Basically, I'll leave most wrapper & packer empty, and focus on the Inter-Machine-Communication stuff, first.

Host
1. Problem divider (divide the problem into smaller ones with different initial argument values)
2. Wrap this oclGA program & sub-problem into an item.
3. Dispatch these items to multiple machines
4. Results collector ( Wait until all items are done )

Client
1. A light-weight listener to receive the sub-problem item.
2. Executor ( Unwrap the item and execute )
3. Results packer ( To pack the results into problem-specific format )
4. A light-weight notifier to notify the result package.

**Comment by kilikkuo** [comment]
I think this issue could be closed by 
1) c8ceab07570baa67c22d040a9eacb7267c2a79fc
2) dedaf675b0e3e12fe85e3f67347523ee23262232
3) https://github.com/kilikkuo/py_simple_host_target/
