### ISSUE TITLE
reverse the min/max calculation

### ISSUE THREAD

**Issue by john-hu** [PyOCL/OpenCLGA#18]
Currently, we use TSP as an example which tries to minimize the path. This doesn't follow the convention of GA. GA tries maximize the fitness value. We should reverse our implementation to follow the convention of GA.

**Comment by kilikkuo** [comment]
https://github.com/PyOCL/oclGA/commit/6a297d24ca82ced5ec1bdf80ab6977f30799ba1b
https://github.com/PyOCL/oclGA/commit/6a1281539423615302dec65dcd9ba3f9abcf6c6f

**Comment by john-hu** [comment]
@kilikkuo 

You can close an issue with the commit with the sentence like this in github:

`Fixed #18 - what had you done`

Once your commit pushed, the issue 18 is closed by itself.

**Comment by kilikkuo** [comment]
Awesome ! Learned : )
