### ISSUE TITLE
Exception Tcl_AsyncDelete: async handler deleted by the wrong thread

### ISSUE THREAD

**Issue by john-hu** [PyOCL/OpenCLGA#23]
```
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x000001FA57641668>>
Traceback (most recent call last):
  File "D:\Program Files\Python35\lib\tkinter\__init__.py", line 3356, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread

```

**Comment by john-hu** [comment]
The link here can solve the problem but the images aren't shown because it may be drawn at an offline memory.

http://stackoverflow.com/questions/27147300/how-to-clean-images-in-python-django

This is not what we want.

**Comment by john-hu** [comment]
API is here: http://matplotlib.org/api/pyplot_api.html  

Currently, I don't know the detailed arguments of show()

**Comment by kilikkuo** [comment]
Moving it to main thread  should fix this. I think you just did

**Comment by john-hu** [comment]
close this issue according to above comment.
