### ISSUE TITLE
rename project name to something related to GA

### ISSUE THREAD

**Issue by john-hu** [PyOCL/OpenCLGA#3]
TSP is a problem name not a good name for GA. We should replace it with another name.

I would suggest:

- clGA
- oclGA
- GAGPU
- PyGAGPU
- pyGG

**Comment by kilikkuo** [comment]
As we're implementing a GA via opencl kernel code.
I'd vote for oclGA, and the original TSP is just an example that what we're gonna solve.

**Comment by john-hu** [comment]
Sure....

**Comment by john-hu** [comment]
Already renamed a few weeks ago.
